### ISSUE TITLE
Dataset Confirmation (Error?)

### ISSUE THREAD

**Issue by xanhho** [allenai/qasper-led-baseline#17]
Hi, thank you for your work.
I have some questions regarding the dataset want to confirm:
1. In table 1: we have four types of answers: Extractive (51.8%), Abstractive (24.2 %), Yes/No (13.9%), and Unanswerable (10.2%). This is over 100%; As I understand, one answer only has one answer type, is it right?
2. In the Dev set, questions_id: "a5e49cdb91d9fd0ca625cc1ede236d3d4672403c", we have one answer like this:
              "unanswerable": true,
              "extractive_spans": [],
              "yes_no": null,
              "free_form_answer": "GRU",
If this is unanswerable,  for "free_form_answer", it should be empty "", is it right?

6a633811019e9323dc8549ad540550d27aa6d972
              "unanswerable": true,
              "extractive_spans": [],
              "yes_no": false,
              "free_form_answer": "",
If it is a yes_no question, for "unanswerable", it should be false? 

a8c862d8c5da3f060eedf3395a3d0a97fd8a12d8
              "unanswerable": true,
              "extractive_spans": [],
              "yes_no": false,
              "free_form_answer": "",
For "yes_no", it should be null?
3. I think these issues also happen with the train set.

**Comment by pdasigi** [comment]
Hi @xanhho!

1. You are right that each answer annotation can have exactly one type. Those numbers add up to 100.1. I am pretty sure it is because of a rounding error.
2. and 3. Thanks a lot for pointing out these issues. I see that 10 annotation the the dev set and 17 annotations in the training set have multiple answer types. This is definitely a mistake. I'll fix the released dataset soon and post an update here.

**Comment by xanhho** [comment]
Hi @pdasigi

Thank you for your quick response.
I'm looking forward to your update.

**Comment by pdasigi** [comment]
Hi @xanhho, the dataset has been updated to fix these issues. Please use v0.3 going forward: https://allenai.org/data/qasper
Thanks!
