### ISSUE TITLE
Question about gold evidence to re-implement table 4 

### ISSUE THREAD

**Issue by Davion-Liu** [allenai/qasper-led-baseline#20]
Hey, I'am trying to re-implement table 4, but I only see the evaluate file, do you have training config?

**Comment by pdasigi** [comment]
Hi @Davion1999, you can use [this config file](https://github.com/allenai/qasper-led-baseline/blob/main/training_config/led_base_smaller_context.jsonnet) to reproduce the LED-base result in table 4.  You'll need to change the `context` in the [`dataset_reader`](https://github.com/allenai/qasper-led-baseline/blob/main/training_config/led_base_smaller_context.jsonnet#L19) and the [`validation_dataset_reader`](https://github.com/allenai/qasper-led-baseline/blob/main/training_config/led_base_smaller_context.jsonnet#L27) to `question_and_evidence`.

Note that your result maybe slightly different from the reported LED-base result because multiple training runs of the LED seem to be resulting in slightly different weights. Check out #18, which reports this issue in the full document setting. I suspect there's a bug in the HuggingFace transformers implementation.

Unfortunately I do not have the hyperparameters used for the T5-large and UnifiedQA-large models. You can use the same config file, and replace the model names to appropriate names from HuggingFace Transformers for these models, and the results should be in the same ball park.

**Comment by usneek** [comment]
@pdasigi, replacing the model name in the config file with T5 does not work. I even tried removing the global attention fields in model.py and setting include_global_attention in dataset_reader.py to false; nevertheless, it did not work, saying nan loss encountered. Could you tell me what mistake I am making?

**Comment by pdasigi** [comment]
@usneek Sorry for the delay in responding to this issue. Did you also change the `max_document_length` to the maximum input length of T5 (512)? Do you see NaNs mid-way in the training, or at the first step itself?

**Comment by usneek** [comment]
Yes, I changed the max_document_length to 512. NaNs are seen in halfway of the first epoch itself. I tried something else. I set the field use_amp to false in the trainer module, which worked well, and I did not see this issue.

**Comment by pdasigi** [comment]
@usneek Good to know that you found a solution. It makes sense that setting `use_amp` to false worked. This flag causes the trainer to use mixed precision training, and it is expected to be more unstable that full precision training.
